services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile        # points to your custom FTS-enabled image
    image: sql-server-fts:2022      # tags the built image locally for reuse
    container_name: sql_architect
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123!"
    volumes:
      - sql_data:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:5341"
      - "8081:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq_data:/data

volumes:
  sql_data:
  seq_data:
